FROM node:22-bookworm-slim AS build
WORKDIR /app
COPY package*.json tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages
RUN npm install && npm run db:generate && npm run build -w @oliveira/api
CMD ["npm","run","start","-w","@oliveira/api"]
