FROM node:22-bookworm-slim
WORKDIR /app
COPY package*.json tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages
RUN npm install && npm run db:generate && npm run build -w @oliveira/worker
CMD ["npm","run","start","-w","@oliveira/worker"]
