FROM node:22-bookworm-slim
WORKDIR /app
COPY package*.json tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages
RUN npm install && npm run build -w @oliveira/runtime-broker
CMD ["npm","run","start","-w","@oliveira/runtime-broker"]
