'use client';
import { useEffect, useState } from 'react';

const API=process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000';
type Step={id:string;key:string;title:string;type:string;agent?:string;status:string;dependsOn:string[];exitCode?:number};
type Gate={command:string;exitCode:number;output:string;ok:boolean};
type ContractFinding={severity:'BLOCK'|'WARN'|'INFO';kind:string;endpoint?:string;message:string};
type ContractGate={ok:boolean;blocking:ContractFinding[];warnings:ContractFinding[];info:ContractFinding[];baseline:{contracts:number;consumers:number;issues:number;highRisk:number};candidate:{contracts:number;consumers:number;issues:number;highRisk:number}};
type ReviewSummary={conflicts?:string[];mergedBranches?:string[];gates?:Gate[];ready?:boolean;contractGate?:ContractGate|null};
type Flow={id:string;title:string;objective:string;status:string;reviewStatus:string;reviewSummary?:ReviewSummary;mergeCommit?:string;steps:Step[]};

export default function OrchestrationsPage(){
 const [workspaceId,setWorkspaceId]=useState(''); const [flows,setFlows]=useState<Flow[]>([]); const [message,setMessage]=useState('');
 async function load(){if(!workspaceId)return;const r=await fetch(`${API}/api/v1/orchestrations?workspaceId=${workspaceId}`,{credentials:'include'});if(r.ok)setFlows(await r.json())}
 useEffect(()=>{const id=new URLSearchParams(location.search).get('workspaceId')??'';setWorkspaceId(id)},[]);
 useEffect(()=>{load();const t=setInterval(load,3000);return()=>clearInterval(t)},[workspaceId]);
 async function action(id:string,path:string){setMessage('Processando...');const r=await fetch(`${API}/api/v1/orchestrations/${id}/${path}`,{method:'POST',credentials:'include'});const data=await r.json().catch(()=>({}));setMessage(r.ok?'Operação concluída.':`Falha: ${data.error??r.status}`);await load()}
 async function createDemo(){const body={workspaceId,title:'Checkout delivery',objective:'Implementar e validar checkout',startNow:true,steps:[{key:'backend',title:'Implementar backend',type:'AGENT',agent:'CODEX',prompt:'Implemente o backend necessário para concluir o checkout. Execute testes relevantes.',dependsOn:[]},{key:'frontend',title:'Revisar frontend',type:'AGENT',agent:'CLAUDE',prompt:'Revise e melhore o frontend do checkout. Preserve a arquitetura existente.',dependsOn:[]},{key:'test',title:'Executar testes',type:'SYSTEM',command:'npm test',dependsOn:['backend','frontend']},{key:'build',title:'Validar build',type:'SYSTEM',command:'npm run build',dependsOn:['test']}]};const r=await fetch(`${API}/api/v1/orchestrations`,{method:'POST',headers:{'content-type':'application/json'},credentials:'include',body:JSON.stringify(body)});setMessage(r.ok?'Orquestração iniciada.':'Falha ao iniciar.');await load()}
 return <main className="page"><div className="hero"><div><span className="eyebrow">REVIEW & MERGE · v2.4</span><h1>Orquestrações</h1><p>Coordene Codex e Claude, execute testes/build e bloqueie regressões de contrato antes do merge final.</p></div><button className="primary" onClick={createDemo} disabled={!workspaceId}>Criar fluxo demonstrativo</button></div>{message&&<p>{message}</p>} {!workspaceId&&<div className="panel"><p>Abra esta página com <code>?workspaceId=...</code>.</p></div>}{flows.map(f=><section className="panel" key={f.id}><div className="row"><div><h2>{f.title}</h2><p>{f.objective}</p></div><div><span className="pill">{f.status}</span> <span className="pill">review: {f.reviewStatus}</span></div></div><div className="row"><div><button onClick={()=>action(f.id,'review/analyze')} disabled={!['WAITING_REVIEW','RUNNING'].includes(f.status)}>Analisar integração</button> <button className="primary" onClick={()=>action(f.id,'review/approve')} disabled={f.reviewStatus!=='READY'}>Aprovar e mesclar</button> <button onClick={()=>action(f.id,'review/reject')} disabled={!['READY','CONFLICT','GATE_FAILED','ANALYZING'].includes(f.reviewStatus)}>Rejeitar review</button></div>{f.mergeCommit&&<code>{f.mergeCommit.slice(0,12)}</code>}</div>{f.reviewSummary&&<div className="card"><h3>Review integrado</h3><p>Branches: {f.reviewSummary.mergedBranches?.join(', ')||'—'}</p><p>Conflitos: {f.reviewSummary.conflicts?.length?f.reviewSummary.conflicts.join(', '):'nenhum'}</p>{f.reviewSummary.gates?.map(g=><div key={g.command}><p><b>{g.ok?'✓':'✗'} {g.command}</b> · exit {g.exitCode}</p>{!g.ok&&<pre style={{whiteSpace:'pre-wrap',maxHeight:220,overflow:'auto'}}>{g.output}</pre>}</div>)}{f.reviewSummary.contractGate&&<div><h3>Contract Gate · {f.reviewSummary.contractGate.ok?'PASS':'BLOCK'}</h3><p>Baseline: {f.reviewSummary.contractGate.baseline.contracts} endpoints · Candidato: {f.reviewSummary.contractGate.candidate.contracts} endpoints</p>{f.reviewSummary.contractGate.blocking.map((x,n)=><p key={`b-${n}`}><b>BLOCK · {x.kind}</b>{x.endpoint?` · ${x.endpoint}`:''}<br/>{x.message}</p>)}{f.reviewSummary.contractGate.warnings.map((x,n)=><p key={`w-${n}`}><b>WARN · {x.kind}</b>{x.endpoint?` · ${x.endpoint}`:''}<br/>{x.message}</p>)}</div>}</div>}<div className="cards">{f.steps.map(s=><article className="card" key={s.id}><span className="eyebrow">{s.type}{s.agent?` · ${s.agent}`:''}</span><h3>{s.title}</h3><p>Status: <b>{s.status}</b></p><p>Depende de: {s.dependsOn.length?s.dependsOn.join(', '):'—'}</p>{s.exitCode!==undefined&&<p>Exit code: {s.exitCode}</p>}</article>)}</div></section>)}</main>
}
