'use client';
import { useEffect, useMemo, useState } from 'react';
import { apiFetch } from '../lib/apiClient';
type Metrics={host:{cpus:number;load:number[];memoryTotal:number;memoryFree:number;uptimeSeconds:number;disk?:{totalBytes:number;freeBytes:number}|null};platform:{runningWorkspaces:number;runningAgents:number;projects:number;runningOrchestrations:number}};
const fmt=(n:number)=>`${(n/1024/1024/1024).toFixed(1)} GB`;
export default function Home(){
 const [metrics,setMetrics]=useState<Metrics|null>(null); const [org,setOrg]=useState(''); const [activity,setActivity]=useState<any[]>([]);
 useEffect(()=>{ const tick=()=>apiFetch('/api/v1/system/metrics-summary').then(r=>r.ok?r.json():null).then(setMetrics).catch(()=>{});tick();const id=setInterval(tick,5000);return()=>clearInterval(id)},[]);
 useEffect(()=>{if(!org){setActivity([]);return} apiFetch(`/api/v1/activity?organizationId=${encodeURIComponent(org)}&limit=8`).then(r=>r.ok?r.json():[]).then(setActivity).catch(()=>setActivity([]))},[org]);
 const mem=useMemo(()=>metrics?Math.round((1-metrics.host.memoryFree/metrics.host.memoryTotal)*100):0,[metrics]);
 return <main className="app-shell"><aside className="sidebar"><div className="brand">OLIVEIRA <span>DEVCLOUD</span></div><div className="nav-group"><small>CONTROL PLANE</small><a className="active" href="/">Overview</a><a href="/projects">Projects</a><a href="/workspaces">Workspaces</a><a href="/agents">Agents</a><a href="/orchestrations">Orchestrations</a></div><div className="nav-group"><small>TOOLS</small><a href="/terminal">Terminal</a><a href="/ide">Browser IDE</a><a href="/import">Import GitHub</a><a href="/repository-map">Repository Map</a><a href="/code-intelligence">Code Intelligence</a><a href="/contract-intelligence">Contract Intelligence</a><a href="/command-center">AI Command Center</a><a href="/settings/secrets">Secrets</a></div><div className="sidebar-foot"><span className="live-dot"/> Control plane online</div></aside><section className="dashboard"><header className="dash-head"><div><p className="eyebrow">OLIVEIRA SYSTEMS · V2.3</p><h1>Development control plane</h1><p className="sub">Workspaces, agents e infraestrutura em uma única visão.</p></div><div className="head-actions"><a className="ghost-link" href="/import">Importar GitHub</a><a className="primary-link" href="/onboarding">+ Novo workspace</a></div></header>
 <div className="metric-grid"><article><span>Workspaces ativos</span><strong>{metrics?.platform.runningWorkspaces ?? '—'}</strong><small>containers em execução</small></article><article><span>Agentes trabalhando</span><strong>{metrics?.platform.runningAgents ?? '—'}</strong><small>Codex + Claude</small></article><article><span>Orquestrações</span><strong>{metrics?.platform.runningOrchestrations ?? '—'}</strong><small>fluxos ativos</small></article><article><span>Projetos</span><strong>{metrics?.platform.projects ?? '—'}</strong><small>registrados</small></article></div>
 <div className="dash-grid"><section className="dash-panel"><div className="panel-title"><div><p className="eyebrow">HOST</p><h2>Recursos do servidor</h2></div><span className="status-pill">LIVE · 5s</span></div><div className="resource-row"><div><span>CPU</span><b>{metrics?.host.cpus ?? '—'} cores</b></div><div className="bar"><i style={{width:`${Math.min(100,((metrics?.host.load?.[0]??0)/(metrics?.host.cpus||1))*100)}%`}}/></div></div><div className="resource-row"><div><span>Memória</span><b>{metrics?`${fmt(metrics.host.memoryTotal-metrics.host.memoryFree)} / ${fmt(metrics.host.memoryTotal)}`:'—'}</b></div><div className="bar"><i style={{width:`${mem}%`}}/></div></div><div className="quick-actions"><a href="/agents">Abrir agentes</a><a href="/orchestrations">Orquestrar tarefa</a><a href="/terminal">Terminal</a><a href="/ide">IDE</a></div></section>
 <section className="dash-panel"><div className="panel-title"><div><p className="eyebrow">ACTIVITY</p><h2>Atividade recente</h2></div></div><label className="org-filter">Organization ID<input value={org} onChange={e=>setOrg(e.target.value)} placeholder="cole o ID para carregar auditoria"/></label><div className="activity-list">{!org&&<p className="empty-copy">Informe a organização para carregar eventos auditados.</p>}{org&&activity.length===0&&<p className="empty-copy">Nenhum evento encontrado.</p>}{activity.map(a=><div className="activity-item" key={a.id}><span className="event-icon">↗</span><div><strong>{a.action.replaceAll('_',' ')}</strong><small>{a.resource} · {new Date(a.createdAt).toLocaleString('pt-BR')}</small></div></div>)}</div></section></div>
 <section className="command-panel"><div><p className="eyebrow">AI COMMAND CENTER</p><h2>Dê um objetivo. O DevCloud organiza o trabalho.</h2><p>Distribua backend, frontend, testes e revisão entre Codex e Claude em worktrees isolados.</p></div><a className="primary-link" href="/orchestrations">Criar orquestração →</a></section></section></main>;
}
