ALTER TABLE "Workspace"
  ADD COLUMN "pidsLimit" INTEGER NOT NULL DEFAULT 512,
  ADD COLUMN "diskMb" INTEGER NOT NULL DEFAULT 10240,
  ADD COLUMN "maxRuntimeMinutes" INTEGER NOT NULL DEFAULT 480,
  ADD COLUMN "runtimeStartedAt" TIMESTAMP(3),
  ADD COLUMN "quotaViolation" TEXT,
  ADD COLUMN "quotaExceededAt" TIMESTAMP(3);

ALTER TABLE "AgentTask"
  ADD COLUMN "maxDurationSeconds" INTEGER NOT NULL DEFAULT 3600;

ALTER TABLE "Orchestration"
  ADD COLUMN "maxDurationSeconds" INTEGER NOT NULL DEFAULT 7200;

ALTER TABLE "SetupJob"
  ADD COLUMN "maxDurationSeconds" INTEGER NOT NULL DEFAULT 1800;
