import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { prisma, Role, WorkspaceStatus, SetupJobStatus, SetupStage } from '@oliveira/database';
import { DockerWorkspaceEngine } from '@oliveira/workspace-engine';
import { detectProject } from '@oliveira/setup-engine';
import { SetupQueue } from '@oliveira/setup-queue';
import { requireOrgRole } from '../lib/auth.js';
import { audit } from '../lib/audit.js';

const workspaces=new DockerWorkspaceEngine(); const setupQueue=new SetupQueue();
async function load(request:FastifyRequest,id:string){const ws=await prisma.workspace.findUnique({where:{id},include:{project:true}});if(!ws)throw Object.assign(new Error('WORKSPACE_NOT_FOUND'),{statusCode:404});const auth=await requireOrgRole(request,ws.project.organizationId,Role.ADMIN);return {ws,...auth}}
const optionsSchema=z.object({clone:z.boolean().default(true),install:z.boolean().default(true),startIde:z.boolean().default(true),registerPorts:z.boolean().default(true),maxDurationSeconds:z.number().int().min(60).max(3600).default(1800)});
async function authorizedJob(request:FastifyRequest,id:string){const job=await prisma.setupJob.findUnique({where:{id},include:{workspace:{include:{project:true}}}});if(!job)throw Object.assign(new Error('SETUP_JOB_NOT_FOUND'),{statusCode:404});const auth=await requireOrgRole(request,job.organizationId,Role.DEVELOPER);return {job,...auth}}

export async function setupRoutes(app:FastifyInstance){
  app.get('/:workspaceId/detect',async request=>{const {workspaceId}=request.params as any;const {ws}=await load(request,workspaceId);if(!ws.containerId||ws.status!==WorkspaceStatus.RUNNING)throw Object.assign(new Error('WORKSPACE_NOT_RUNNING'),{statusCode:409});return detectProject(ws.containerId)});
  app.post('/:workspaceId/provision',async (request,reply)=>{const {workspaceId}=request.params as any;const parsed=optionsSchema.parse(request.body??{});const {maxDurationSeconds,...options}=parsed;const {ws,user}=await load(request,workspaceId);if(!ws.containerId||ws.status!==WorkspaceStatus.RUNNING)throw Object.assign(new Error('WORKSPACE_NOT_RUNNING'),{statusCode:409});const active=await prisma.setupJob.findFirst({where:{workspaceId,status:{in:[SetupJobStatus.QUEUED,SetupJobStatus.RUNNING,SetupJobStatus.CANCEL_REQUESTED]}},orderBy:{createdAt:'desc'}});if(active)return reply.code(202).send(active);const job=await prisma.setupJob.create({data:{workspaceId,userId:user.id,organizationId:ws.project.organizationId,options,maxDurationSeconds}});await prisma.setupJobLog.create({data:{setupJobId:job.id,stage:SetupStage.QUEUED,message:'Provisionamento adicionado à fila'}});await setupQueue.enqueue(job.id);await audit({userId:user.id,organizationId:ws.project.organizationId,action:'WORKSPACE_PROVISION_QUEUED',resource:'SetupJob',resourceId:job.id,ipAddress:request.ip,metadata:{maxDurationSeconds}});return reply.code(202).send(job)});
  app.get('/jobs/:jobId',async request=>{const {jobId}=request.params as any;const {job}=await authorizedJob(request,jobId);return job});
  app.get('/jobs/:jobId/logs',async request=>{const {jobId}=request.params as any;await authorizedJob(request,jobId);return prisma.setupJobLog.findMany({where:{setupJobId:jobId},orderBy:{createdAt:'asc'},take:1000})});
  app.get('/jobs/:jobId/events',async (request,reply)=>{const {jobId}=request.params as any;await authorizedJob(request,jobId);reply.hijack();reply.raw.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-transform','Connection':'keep-alive','X-Accel-Buffering':'no'});let last='';let closed=false;request.raw.on('close',()=>{closed=true});while(!closed){const job=await prisma.setupJob.findUnique({where:{id:jobId}});if(!job)break;const logs=await prisma.setupJobLog.findMany({where:{setupJobId:jobId},orderBy:{createdAt:'asc'},take:1000});const payload=JSON.stringify({job,logs});if(payload!==last){reply.raw.write(`event: setup\ndata: ${payload}\n\n`);last=payload}if([SetupJobStatus.READY,SetupJobStatus.FAILED,SetupJobStatus.CANCELLED].includes(job.status as any)){reply.raw.write('event: end\ndata: {}\n\n');break}await new Promise(r=>setTimeout(r,1000))}reply.raw.end()});
  app.post('/jobs/:jobId/cancel',async (request,reply)=>{const {jobId}=request.params as any;const {job,user}=await authorizedJob(request,jobId);await requireOrgRole(request,job.organizationId,Role.ADMIN);const now=new Date();const queued=await prisma.setupJob.updateMany({where:{id:job.id,status:SetupJobStatus.QUEUED},data:{status:SetupJobStatus.CANCELLED,stage:SetupStage.CANCELLED,message:'Cancelado antes da execução',finishedAt:now,heartbeatAt:now}});if(queued.count>0){await setupQueue.remove(job.id).catch(()=>undefined);await prisma.setupJobLog.create({data:{setupJobId:job.id,stage:SetupStage.CANCELLED,level:'WARN',message:'Provisionamento cancelado pelo usuário'}});await audit({userId:user.id,organizationId:job.organizationId,action:'WORKSPACE_PROVISION_CANCELLED',resource:'SetupJob',resourceId:job.id,ipAddress:request.ip,metadata:{previousStatus:SetupJobStatus.QUEUED}});return prisma.setupJob.findUniqueOrThrow({where:{id:job.id}})}const running=await prisma.setupJob.updateMany({where:{id:job.id,status:SetupJobStatus.RUNNING},data:{status:SetupJobStatus.CANCEL_REQUESTED,message:'Cancelamento solicitado',heartbeatAt:now}});if(running.count>0){await prisma.setupJobLog.create({data:{setupJobId:job.id,level:'WARN',message:'Cancelamento solicitado; será aplicado no próximo checkpoint'}});await audit({userId:user.id,organizationId:job.organizationId,action:'WORKSPACE_PROVISION_CANCEL_REQUESTED',resource:'SetupJob',resourceId:job.id,ipAddress:request.ip});return reply.code(202).send(await prisma.setupJob.findUniqueOrThrow({where:{id:job.id}}))}const current=await prisma.setupJob.findUniqueOrThrow({where:{id:job.id}});if(current.status===SetupJobStatus.CANCEL_REQUESTED)return reply.code(202).send(current);if(current.status===SetupJobStatus.CANCELLED)return current;return reply.code(409).send({error:'SETUP_JOB_ALREADY_TERMINAL'})});
  app.post('/jobs/:jobId/retry',async (request,reply)=>{const {jobId}=request.params as any;const {job,user}=await authorizedJob(request,jobId);await requireOrgRole(request,job.organizationId,Role.ADMIN);if(![SetupJobStatus.FAILED,SetupJobStatus.CANCELLED].includes(job.status as any))return reply.code(409).send({error:'SETUP_JOB_NOT_RETRYABLE'});const next=await prisma.setupJob.create({data:{workspaceId:job.workspaceId,userId:user.id,organizationId:job.organizationId,options:job.options??undefined,maxDurationSeconds:job.maxDurationSeconds,attempt:job.attempt+1,parentJobId:job.id}});await prisma.setupJobLog.create({data:{setupJobId:next.id,stage:SetupStage.QUEUED,message:`Nova tentativa #${next.attempt} criada a partir de ${job.id}`}});await setupQueue.enqueue(next.id);await audit({userId:user.id,organizationId:job.organizationId,action:'WORKSPACE_PROVISION_RETRIED',resource:'SetupJob',resourceId:next.id,ipAddress:request.ip});return reply.code(202).send(next)});
  app.get('/:workspaceId/jobs/latest',async request=>{const {workspaceId}=request.params as any;await load(request,workspaceId);const job=await prisma.setupJob.findFirst({where:{workspaceId},orderBy:{createdAt:'desc'}});if(!job)throw Object.assign(new Error('SETUP_JOB_NOT_FOUND'),{statusCode:404});return job});
  app.post('/quickstart',async (request,reply)=>{const body=z.object({projectId:z.string().cuid(),cpuLimit:z.number().min(.25).max(16).default(1),memoryMb:z.number().int().min(256).max(32768).default(2048),pidsLimit:z.number().int().min(64).max(4096).default(512),diskMb:z.number().int().min(512).max(102400).default(10240),maxRuntimeMinutes:z.number().int().min(15).max(10080).default(480)}).parse(request.body);const project=await prisma.project.findUnique({where:{id:body.projectId}});if(!project)throw Object.assign(new Error('PROJECT_NOT_FOUND'),{statusCode:404});const {user}=await requireOrgRole(request,project.organizationId,Role.ADMIN);const row=await prisma.workspace.create({data:{projectId:project.id,cpuLimit:body.cpuLimit,memoryMb:body.memoryMb,pidsLimit:body.pidsLimit,diskMb:body.diskMb,maxRuntimeMinutes:body.maxRuntimeMinutes,status:WorkspaceStatus.CREATING}});try{const runtime=await workspaces.create({workspaceId:row.id,projectId:project.id,repositoryUrl:project.repositoryUrl,defaultBranch:project.defaultBranch,limits:body});const now=new Date();await prisma.workspace.update({where:{id:row.id},data:{containerId:runtime.containerId,status:WorkspaceStatus.RUNNING,heartbeatAt:now,runtimeStartedAt:now}});await audit({userId:user.id,organizationId:project.organizationId,action:'WORKSPACE_QUICKSTART_CREATED',resource:'Workspace',resourceId:row.id,ipAddress:request.ip,metadata:{cpuLimit:body.cpuLimit,memoryMb:body.memoryMb,pidsLimit:body.pidsLimit,diskMb:body.diskMb,maxRuntimeMinutes:body.maxRuntimeMinutes}});return reply.code(201).send({workspaceId:row.id,status:'RUNNING',next:`/api/v1/setup/${row.id}/provision`})}catch(e){await prisma.workspace.update({where:{id:row.id},data:{status:WorkspaceStatus.ERROR}});throw e}})
}
