import { RuntimeBrokerClient } from '@oliveira/runtime-broker-client';
const broker=new RuntimeBrokerClient();
const MAX_FILES=180, MAX_BYTES=22000, MAX_CONTRACTS=240, MAX_CONSUMERS=260;
export type ContractField={name:string;type?:string;required?:boolean};
export type ApiContract={id:string;method:string;path:string;file:string;line:number;requestFields:ContractField[];responseFields:ContractField[];schemaHints:string[]};
export type ApiConsumer={id:string;method:string;path:string;file:string;line:number;requestFields:string[];responseFields:string[]};
export type ContractIssue={severity:'HIGH'|'MEDIUM'|'LOW';kind:'MISSING_ENDPOINT'|'METHOD_MISMATCH'|'REQUEST_FIELD_MISMATCH'|'RESPONSE_FIELD_MISMATCH';producerId?:string;consumerId?:string;message:string};
export type ContractIntelligence={generatedAt:string;filesAnalyzed:number;contracts:ApiContract[];consumers:ApiConsumer[];issues:ContractIssue[];summary:{contracts:number;consumers:number;issues:number;highRisk:number};warnings:string[]};
async function exec(containerId:string,cmd:string[],workingDir='/workspace/repository'){return broker.exec(containerId,{cmd,workingDir,user:'devcloud'})}
function lineOf(text:string,index:number){return text.slice(0,index).split(/\r?\n/).length}
function normPath(v:string){if(!v)return'/';let x=v.replace(/\$\{[^}]+\}/g,':param').replace(/\/+/g,'/');if(!x.startsWith('/'))x='/'+x;return x.replace(/\/$/,'')||'/'}
function id(file:string,line:number,kind:string){return`${file}:${line}:${kind}`.replace(/[^a-zA-Z0-9_./:-]/g,'_').slice(0,220)}
function objectKeys(fragment:string){const out:string[]=[];for(const m of fragment.matchAll(/(?:^|[,\n{])\s*([A-Za-z_$][\w$]*)\s*:/g)){if(!out.includes(m[1]))out.push(m[1]);if(out.length>=30)break}return out}
function nearby(text:string,index:number,radius=2200){return text.slice(Math.max(0,index-radius),Math.min(text.length,index+radius))}
function schemaHints(fragment:string){const out:string[]=[];for(const m of fragment.matchAll(/\b([A-Z][A-Za-z0-9_$]*(?:Schema|Dto|DTO|Request|Response|Input|Output))\b/g)){if(!out.includes(m[1]))out.push(m[1]);if(out.length>=12)break}return out}
function requestFields(fragment:string){const names=new Set<string>();for(const re of [/\.body\s*(?:as\s+[^;\n]+)?/g,/z\.object\s*\(\s*\{([\s\S]{0,1600}?)\}\s*\)/g,/body\s*:\s*\{([\s\S]{0,1000}?)\}/g])for(const m of fragment.matchAll(re)){const part=m[1]??m[0];for(const k of objectKeys(part))names.add(k)}return Array.from(names).slice(0,30).map(name=>({name}));}
function responseFields(fragment:string){const names=new Set<string>();for(const m of fragment.matchAll(/(?:send|json|reply\.code\([^)]*\)\.send)\s*\(\s*\{([\s\S]{0,1200}?)\}\s*\)/g))for(const k of objectKeys(m[1]))names.add(k);for(const m of fragment.matchAll(/return\s+\{([\s\S]{0,1000}?)\}/g))for(const k of objectKeys(m[1]))names.add(k);return Array.from(names).slice(0,30).map(name=>({name}));}
function consumersFromTs(file:string,text:string){const out:ApiConsumer[]=[];for(const m of text.matchAll(/fetch\s*\(\s*([`'"])(.*?)\1\s*,?\s*([\s\S]{0,900}?)\)/g)){if(out.length>=MAX_CONSUMERS)break;const opts=m[3]??'';const mm=opts.match(/method\s*:\s*['"]([A-Z]+)['"]/i);const method=(mm?.[1]??'GET').toUpperCase();const path=normPath(m[2].replace(/^https?:\/\/[^/]+/,'').replace(/^\$\{[^}]+\}/,''));const req:string[]=[];const bm=opts.match(/body\s*:\s*JSON\.stringify\s*\(\s*\{([\s\S]{0,700}?)\}\s*\)/);if(bm)req.push(...objectKeys(bm[1]));out.push({id:id(file,lineOf(text,m.index??0),'consumer'),method,path,file,line:lineOf(text,m.index??0),requestFields:req,responseFields:[]})}
for(const m of text.matchAll(/\b(?:axios|api|client)\.(get|post|put|patch|delete)\s*\(\s*['"`]([^'"`]+)['"`]\s*(?:,\s*\{([\s\S]{0,700}?)\})?/gi)){const method=m[1].toUpperCase(),path=normPath(m[2]);out.push({id:id(file,lineOf(text,m.index??0),'consumer'),method,path,file,line:lineOf(text,m.index??0),requestFields:m[3]?objectKeys(m[3]):[],responseFields:[]})}return out;}
export async function listContractFiles(containerId:string,workingDir='/workspace/repository'):Promise<string[]>{const r=await exec(containerId,['git','ls-files','--cached','--others','--exclude-standard'],workingDir);if(r.exitCode!==0)throw new Error('CONTRACT_FILE_LIST_FAILED');return r.output.split(/\r?\n/).map(x=>x.trim()).filter(f=>/\.(ts|tsx|js|jsx|java)$/.test(f)).slice(0,MAX_FILES)}
export async function inspectContracts(containerId:string,filesInput:string[],workingDir='/workspace/repository'):Promise<ContractIntelligence>{const files=filesInput.filter(f=>/\.(ts|tsx|js|jsx|java)$/.test(f)).slice(0,MAX_FILES),contracts:ApiContract[]=[],consumers:ApiConsumer[]=[],warnings:string[]=[];for(const file of files){const r=await exec(containerId,['cat','--',file],workingDir);if(r.exitCode!==0){warnings.push(`READ_FAILED:${file}`);continue}const text=r.output.slice(0,MAX_BYTES);if(r.output.length>MAX_BYTES)warnings.push(`TRUNCATED:${file}`);if(/\.(ts|tsx|js|jsx)$/.test(file)){for(const m of text.matchAll(/\b(?:app|router|server)\.(get|post|put|patch|delete|options|head)\s*\(\s*['"`]([^'"`]+)['"`]/gi)){if(contracts.length>=MAX_CONTRACTS)break;const frag=nearby(text,m.index??0);contracts.push({id:id(file,lineOf(text,m.index??0),'contract'),method:m[1].toUpperCase(),path:normPath(m[2]),file,line:lineOf(text,m.index??0),requestFields:requestFields(frag),responseFields:responseFields(frag),schemaHints:schemaHints(frag)})}consumers.push(...consumersFromTs(file,text).slice(0,MAX_CONSUMERS-consumers.length));}else if(file.endsWith('.java')){const classBase=(text.match(/@RequestMapping\s*\(\s*["']([^"']*)["']/)?.[1])??'';for(const m of text.matchAll(/@(GetMapping|PostMapping|PutMapping|PatchMapping|DeleteMapping)\s*(?:\(\s*["']([^"']*)["']\s*\))?/g)){if(contracts.length>=MAX_CONTRACTS)break;const method=m[1].replace('Mapping','').toUpperCase();const frag=nearby(text,m.index??0);contracts.push({id:id(file,lineOf(text,m.index??0),'contract'),method,path:normPath(`${classBase}/${m[2]??''}`),file,line:lineOf(text,m.index??0),requestFields:[],responseFields:[],schemaHints:schemaHints(frag)})}}}
const issues:ContractIssue[]=[];const byPath=new Map<string,ApiContract[]>();for(const c of contracts){const a=byPath.get(c.path)??[];a.push(c);byPath.set(c.path,a)}for(const c of consumers){const same=byPath.get(c.path)??[];if(!same.length){issues.push({severity:'HIGH',kind:'MISSING_ENDPOINT',consumerId:c.id,message:`Consumidor usa ${c.method} ${c.path}, mas nenhum endpoint correspondente foi detectado.`});continue}const exact=same.find(x=>x.method===c.method);if(!exact){issues.push({severity:'HIGH',kind:'METHOD_MISMATCH',consumerId:c.id,producerId:same[0].id,message:`Consumidor usa ${c.method} ${c.path}, porém o backend detectado expõe ${same.map(x=>x.method).join('/')}.`});continue}const producerReq=new Set(exact.requestFields.map(x=>x.name));for(const f of c.requestFields)if(producerReq.size&& !producerReq.has(f))issues.push({severity:'MEDIUM',kind:'REQUEST_FIELD_MISMATCH',consumerId:c.id,producerId:exact.id,message:`Campo '${f}' enviado pelo consumidor não aparece no request inferido de ${exact.method} ${exact.path}.`})}
return{generatedAt:new Date().toISOString(),filesAnalyzed:files.length,contracts,consumers:consumers.slice(0,MAX_CONSUMERS),issues:issues.slice(0,300),summary:{contracts:contracts.length,consumers:consumers.length,issues:issues.length,highRisk:issues.filter(i=>i.severity==='HIGH').length},warnings};}
