import Docker from 'dockerode';
const docker=new Docker({socketPath:process.env.DOCKER_SOCKET??'/var/run/docker.sock'});
const MAX_FILES=140,MAX_BYTES=18000,MAX_SYMBOLS=1200,MAX_EDGES=1600;
export type SymbolKind='class'|'function'|'component'|'method'|'route'|'model'|'interface'|'type';
export type CodeSymbol={id:string;name:string;kind:SymbolKind;file:string;line:number;exported?:boolean;signature?:string};
export type CodeEdge={from:string;to:string;type:'imports'|'calls'|'extends'|'route-handler'};
export type CodeEndpoint={method:string;path:string;file:string;handler?:string;line:number};
export type CodeIntelligence={generatedAt:string;filesAnalyzed:number;symbols:CodeSymbol[];edges:CodeEdge[];endpoints:CodeEndpoint[];summary:{classes:number;functions:number;components:number;routes:number;models:number};warnings:string[]};
async function exec(containerId:string,cmd:string[]){const c=docker.getContainer(containerId);const e=await c.exec({Cmd:cmd,WorkingDir:'/workspace/repository',User:'devcloud',AttachStdout:true,AttachStderr:true});const s=await e.start({hijack:true,stdin:false});let out='';for await(const b of s as any){if(out.length<MAX_BYTES*MAX_FILES)out+=Buffer.from(b).toString('utf8')}const i=await e.inspect();return{exitCode:i.ExitCode??1,output:out}}
function escId(s:string){return s.replace(/[^a-zA-Z0-9_./:-]/g,'_').slice(0,180)}
function lineOf(text:string,index:number){return text.slice(0,index).split(/\r?\n/).length}
function addSymbol(arr:CodeSymbol[],file:string,text:string,re:RegExp,kind:SymbolKind,nameGroup=1){for(const m of text.matchAll(re)){if(arr.length>=MAX_SYMBOLS)break;const name=m[nameGroup];if(!name)continue;arr.push({id:escId(`${file}:${kind}:${name}:${lineOf(text,m.index??0)}`),name,kind,file,line:lineOf(text,m.index??0),exported:/^export\s/m.test(m[0]),signature:m[0].trim().slice(0,220)})}}
function localImportTarget(from:string,spec:string,files:Set<string>){if(!spec.startsWith('.'))return null;const parts=from.split('/');parts.pop();for(const seg of spec.split('/')){if(seg==='.'||!seg)continue;if(seg==='..')parts.pop();else parts.push(seg)}const base=parts.join('/');for(const c of [base,base+'.ts',base+'.tsx',base+'.js',base+'.jsx',base+'.py',base+'/index.ts',base+'/index.tsx',base+'/index.js'])if(files.has(c))return c;return null}
export async function inspectCode(containerId:string,filesInput:string[]):Promise<CodeIntelligence>{const warnings:string[]=[];const files=filesInput.filter(f=>/\.(ts|tsx|js|jsx|py|java)$/.test(f)).slice(0,MAX_FILES);const fileSet=new Set(filesInput);const symbols:CodeSymbol[]=[],edges:CodeEdge[]=[],endpoints:CodeEndpoint[]=[];
for(const file of files){const r=await exec(containerId,['cat','--',file]);if(r.exitCode!==0){warnings.push(`READ_FAILED:${file}`);continue}const text=r.output.slice(0,MAX_BYTES);if(r.output.length>MAX_BYTES)warnings.push(`TRUNCATED:${file}`);
if(/\.(ts|tsx|js|jsx)$/.test(file)){addSymbol(symbols,file,text,/(?:export\s+)?class\s+([A-Za-z_$][\w$]*)[^\n{]*/g,'class');addSymbol(symbols,file,text,/(?:export\s+)?(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\([^)]*\)/g,'function');addSymbol(symbols,file,text,/(?:export\s+)?(?:const|let)\s+([A-Z][A-Za-z0-9_$]*)\s*=\s*(?:async\s*)?\([^)]*\)\s*=>/g,'component');addSymbol(symbols,file,text,/(?:export\s+)?interface\s+([A-Za-z_$][\w$]*)/g,'interface');addSymbol(symbols,file,text,/(?:export\s+)?type\s+([A-Za-z_$][\w$]*)\s*=/g,'type');
for(const m of text.matchAll(/\b(app|router)\.(get|post|put|patch|delete|options|head)\s*\(\s*['"`]([^'"`]+)['"`]/gi))endpoints.push({method:m[2].toUpperCase(),path:m[3],file,line:lineOf(text,m.index??0)});
for(const m of text.matchAll(/(?:import[^'"`]*from\s*|require\s*\(\s*)['"`]([^'"`]+)['"`]/g)){const to=localImportTarget(file,m[1],fileSet);if(to&&edges.length<MAX_EDGES)edges.push({from:file,to,type:'imports'})}}
else if(file.endsWith('.py')){addSymbol(symbols,file,text,/^class\s+([A-Za-z_]\w*)[^:]*:/gm,'class');addSymbol(symbols,file,text,/^(?:async\s+)?def\s+([A-Za-z_]\w*)\s*\([^)]*\)/gm,'function');for(const m of text.matchAll(/^(?:from\s+([\w.]+)\s+import|import\s+([\w.]+))/gm)){const mod=(m[1]||m[2]||'').replace(/\./g,'/');const to=[mod+'.py',mod+'/__init__.py'].find(x=>fileSet.has(x));if(to&&edges.length<MAX_EDGES)edges.push({from:file,to,type:'imports'})}}
else if(file.endsWith('.java')){addSymbol(symbols,file,text,/(?:public\s+)?(?:abstract\s+)?class\s+([A-Za-z_]\w*)/g,'class');addSymbol(symbols,file,text,/(?:public|protected|private)\s+(?:static\s+)?[\w<>\[\], ?]+\s+([A-Za-z_]\w*)\s*\([^;{}]*\)\s*\{/g,'method');for(const m of text.matchAll(/@(GetMapping|PostMapping|PutMapping|PatchMapping|DeleteMapping)\s*(?:\(\s*["']([^"']*)["']\s*\))?/g)){const method=m[1].replace('Mapping','').toUpperCase();endpoints.push({method,path:m[2]||'/',file,line:lineOf(text,m.index??0)})}}
}
const summary={classes:symbols.filter(s=>s.kind==='class').length,functions:symbols.filter(s=>s.kind==='function'||s.kind==='method').length,components:symbols.filter(s=>s.kind==='component').length,routes:endpoints.length,models:symbols.filter(s=>s.kind==='model').length};return{generatedAt:new Date().toISOString(),filesAnalyzed:files.length,symbols,edges,endpoints,summary,warnings}}
